
services:
  mysql:
    image: mysql:8.0
    container_name: ddabong
    ports:
      - 3308:3306
    expose:
      - 3308
    environment:
      MYSQL_ROOT_PASSWORD: Ekqhd7!
      MYSQL_DATABASE: ddabong
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --log_bin_trust_function_creators=1
      - --default-time-zone=Asia/Seoul

    volumes:
      - ./mysql:/var/lib/mysql

  redis:
    image: redis:7.2.4
    container_name: redis-local
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
volumes:
  redis-data:
